---
logging:
  level:
    root: INFO
    #root: WARN
    #root: DEBUG
    #org.springframework.security: TRACE
    org.hibernate: "error"

spring:
  profiles:
    default: dev
    #active: dev
    #active: prod
  application:
    name: app
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  instancio:
    bean:
      validation:
        enabled: true
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
      #ddl-auto: update
      #ddl-auto: validate

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  port: 8080
  address: 0.0.0.0

sentry:
  dsn: https://07575dd331fdc51c7f158b72c580d6ed@o4510381200179204.ingest.de.sentry.io/4510390701916240
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true

